version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  frontend:
    image: insurance-frontend:latest
    build: ./frontend
    ports:
      - "80:80"
    links:
      - backend:backend
  backend:
    image: insurance-backend:latest
    build: ./backend
    links:
      - db:db
    volumes:
      - ./application.properties:/app/application.properties